name: Tests

on:
  workflow_call:
    inputs:
      test-cmd:
        required: false
        type: string
        default: echo "No test command specified."
      slack-before-message:
        required: false
        type: string
      slack-after-message:
        required: false
        type: string
      slack-ts:
        required: false
        type: string
        default: ''
      slack-channel-id:
        required: false
        type: string
      environment:
        required: false
        type: string
        default: default
    secrets:
      slack-bot-token:
        required: false
    outputs:
      ts: 
        value: ${{ jobs.test.outputs.ts }}
      message:
        value: ${{ jobs.test.outputs.message }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      ts: ${{ steps.slack-after.outputs.ts }}
      message: ${{ steps.slack-after.outputs.message }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: slack-before
      if: inputs.slack-before-message != null
      uses: ./.github/actions/slack-post
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        slack-bot-token: ${{ secrets.slack-bot-token }}
        message: ${{ inputs.slack-before-message }}
        ts: ${{ inputs.slack-ts }}

    - name: Running tests
      run: ${{ inputs.test-cmd }}

    - id: slack-after
      if: inputs.slack-after-message != null
      uses: ./.github/actions/slack-post
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        slack-bot-token: ${{ secrets.slack-bot-token }}
        ts: ${{ steps.slack-before.outputs.ts }}
        message: ${{ inputs.slack-after-message }}