name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      service-account:
        required: true
        type: string
      image:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      location:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: default
      manifest-dir:
        required: false
        type: string
        default: .k8s
    secrets:
      workload-identity-provider:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
      actions: read
    outputs:
      ts: ${{ steps.slack-after.outputs.ts }}
      message: ${{ steps.slack-after.outputs.message }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        service_account: ${{ inputs.service-account }}
        workload_identity_provider: ${{ secrets.workload-identity-provider }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Fetch Kubernetes credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        location: ${{ inputs.location }}

    - name: Reject canary
      uses: Azure/k8s-deploy@v4
      with:
        namespace: ${{ inputs.namespace }}
        pull-images: false
        strategy: canary
        action: reject
        manifests: ${{ inputs.manifest-dir }}
        images: ${{ inputs.image }}