name: Build Docker image

on:
  workflow_call:
    inputs:
      service-account:
        required: true
        type: string
      image:
        required: true
        type: string
      slack-before-message:
        required: false
        type: string
      slack-after-message:
        required: false
        type: string
      slack-ts:
        required: false
        type: string
        default: ''
    secrets:
      workload-identity-provider:
        required: true
      slack-bot-token:
        required: false
      slack-channel-id:
        required: false
    outputs:
      ts:
        value: ${{ jobs.build.outputs.ts }}
      message:
        value: ${{ jobs.build.outputs.message }}
      image:
        value: ${{ inputs.image }}:${{ github.sha }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      ts: ${{ steps.slack-after.outputs.ts }}
      message: ${{ steps.slack-after.outputs.message }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: slack-before
      if: inputs.slack-before-message != null
      uses: ./.github/actions/slack-post
      with:
        channel-id: ${{ secrets.slack-channel-id }}
        slack-bot-token: ${{ secrets.slack-bot-token }}
        message: ${{ inputs.slack-before-message }}
        ts: ${{ inputs.slack-ts }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v0
      with:
        service_account: ${{ inputs.service-account }}
        workload_identity_provider: ${{ secrets.workload-identity-provider }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Configure Docker
      run: gcloud --quiet auth configure-docker

    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ inputs.image }}:${{ github.sha }}
          ${{ inputs.image }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - id: slack-after
      if: inputs.slack-after-message != null
      uses: ./.github/actions/slack-post
      with:
        channel-id: ${{ secrets.slack-channel-id }}
        slack-bot-token: ${{ secrets.slack-bot-token }}
        ts: ${{ steps.slack-before.outputs.ts }}
        message: ${{ inputs.slack-after-message }}