name: Observe metrics

on:
  workflow_call:
    inputs:
      metrics:
        required: false
        type: string
        default: ''
      slack-before-message:
        required: false
        type: string
      slack-after-message:
        required: false
        type: string
      slack-ts:
        required: false
        type: string
        default: ''
      slack-channel-id:
        required: false
        type: string
      environment:
        required: false
        type: string
        default: default
    secrets:
      slack-bot-token:
        required: false
    outputs:
      ts:
        value: ${{ jobs.observe.outputs.ts }}
      message:
        value: ${{ jobs.observe.outputs.message }}
      healthy:
        value: ${{ jobs.observe.outputs.healthy }}

jobs:
  observe:
    name: Observe metrics
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      ts: ${{ steps.slack-after.outputs.ts }}
      message: ${{ steps.slack-after.outputs.message }}
      healthy: ${{ steps.evaluation.outputs.healthy }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: slack-before
      if: inputs.slack-before-message != null
      uses: ./.github/actions/slack-post
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        slack-bot-token: ${{ secrets.slack-bot-token }}
        message: ${{ inputs.slack-before-message }}
        ts: ${{ inputs.slack-ts }}

    - name: Gathering metrics
      run: echo "Gathering metrics from observability system (mock)"; sleep 30;

    - name: Evaluating metrics
      id: evaluation
      run: |
        echo "Evaluating metrics (mock)";
        echo "healthy=$(if [ $(($RANDOM % 2)) -eq 1 ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

    - id: slack-after
      if: inputs.slack-after-message != null
      uses: ./.github/actions/slack-post
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        slack-bot-token: ${{ secrets.slack-bot-token }}
        ts: ${{ steps.slack-before.outputs.ts }}
        message: ${{ inputs.slack-after-message }}